#!/bin/bash

cd -- "$(dirname "$0")"
if test -z "$FALSE"; then
	FALSE=../false
fi
t="$PREFIX $FALSE"

report ()
{
	if test $1 = 0; then
		printf "\033[1;32mTest %s OK\033[m\n" "$2"
	else
		printf "\033[1;31mTest %s FAILED\033[m\n" "$2"
	fi
}

F ()
{
	touch tmp1 tmp2; rm tmp1 tmp2
	! $t "$@" 2> tmp1 >&2
	ret=$?
	< tmp1 tee /dev/stderr | grep -v '^==[0-9]*==' > tmp2
	test $ret = 0 && test ! -s tmp2
	ret=$?
	rm tmp1 tmp2
	return $ret
}



args0 ()
{
	F
	report $? "args0"
}

args1 ()
{
	F 1
	report $? "args1"
}

args2 ()
{
	F 1 2
	report $? "args2"
}

args3 ()
{
	F 1 2 3
	report $? "args3"
}

dash ()
{
	F -
	report $? "dash"
}

opt ()
{
	F -h
	report $? "opt"
}

ddash ()
{
	F --
	report $? "ddash"
}

long ()
{
	F --hello
	report $? "long"
}



if test $# = 0; then
	set args0 args1 args2 args3 dash opt ddash long
fi
(
for f in $@; do
	$f
done
) | tee result
! grep FAILED < result > /dev/null
ret=$?
if test $ret != 0; then
	if test $(grep FAILED < result | grep -v NON-STANDARD | wc -l) = 0; then
		ret=1
	else
		ret=2
	fi
fi
rm result
exit $ret
